// Generated by God Tools~/SyncEditorTheme.ps1. Edit the canonical God theme, then regenerate.
// IMPORTANT: This script must comply with GeurtsGameForgeDocumentation/GeurtsTechniques/GeurtsTechnicalTechnique.md and folder placement rules in GeurtsGameForgeDocumentation/GeurtsTechniques/GeurtsFolderStructureTechnique.md.
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;
#if ODIN_INSPECTOR
using Sirenix.Utilities.Editor;
#endif

namespace Geurts.GameForge.Documentation
{
    /// <summary>Shared dark/green Editor presentation for Geurts Game Forge tools and owned inspectors.</summary>
    internal sealed class DocumentationEditorTheme : IDisposable
    {
        /// <summary>Revision of the shared visual contract, independent of package version.</summary>
        public const string StandardVersion = "1.2.0";
        private const string StyleSheetPath = "Packages/com.geurts.gameforge.documentation/Editor/DocumentationEditorTheme.uss";
        /// <summary>Root class that confines UI Toolkit styling to the owning Forge surface.</summary>
        public const string RootClass = "geurts-forge";
        /// <summary>Near-black canvas.</summary>
        public static readonly Color Background = new Color32(10, 16, 18, 255);
        /// <summary>Primary card surface.</summary>
        public static readonly Color Panel = new Color32(18, 28, 30, 255);
        /// <summary>Raised or hovered surface.</summary>
        public static readonly Color Raised = new Color32(23, 36, 37, 255);
        /// <summary>Quiet structural border.</summary>
        public static readonly Color Border = new Color32(43, 67, 63, 255);
        /// <summary>Primary action, selection and success accent.</summary>
        public static readonly Color Green = new Color32(110, 242, 157, 255);
        /// <summary>Primary readable text.</summary>
        public static readonly Color Text = new Color32(222, 236, 231, 255);
        /// <summary>Secondary readable text.</summary>
        public static readonly Color Muted = new Color32(143, 168, 161, 255);
        /// <summary>Warning accent. Always pair with a written state.</summary>
        public static readonly Color Warning = new Color32(255, 230, 109, 255);
        /// <summary>Error/destructive/development-warning accent. Always pair with text.</summary>
        public static readonly Color Error = new Color32(255, 107, 107, 255);

        private readonly List<Texture2D> _textures = new List<Texture2D>();
        /// <summary>Owned, cached styles. Reuse these for all IMGUI/Odin presentation in the surface.</summary>
        public readonly GUIStyle Window, Title, Eyebrow, Body, Small, Section, Foldout, Button, SelectedButton, DangerButton, Log, Card, Inspection;
        private GUISkin _skin;
        private readonly List<GUIStyle> _readableStyles = new List<GUIStyle>();
        private Color[] _savedColors;
        private GUISkin _previousSkin;
        private int _scopeDepth;
        private readonly List<GUIStyle> _buttonStyles = new List<GUIStyle>();
        private readonly List<GUIStyle> _panelStyles = new List<GUIStyle>();
        private Texture2D[] _savedBackgrounds;
        private Color[] _savedControlColors;
        private RectOffset[] _savedBorders;
        private readonly RectOffset _thinBorder = new RectOffset(1, 1, 1, 1);

        /// <summary>Opens a resizable Forge window with a spacious initial size; an existing window keeps its layout.</summary>
        /// <param name="minimumSize">The window's smallest supported content size, in Editor points.</param>
        /// <param name="title">Optional title for a newly created window.</param>
        /// <returns>The existing or newly opened window.</returns>
        public static T OpenWindow<T>(Vector2 minimumSize, string title = null) where T : EditorWindow
        {
            bool alreadyOpen = EditorWindow.HasOpenInstances<T>();
            T window = EditorWindow.GetWindow<T>(title);
            if (alreadyOpen || window.docked || window.maximized) return window;

            window.minSize = minimumSize;
            // Fit the preferred size to the main Editor area while retaining the window's supported minimum.
            Rect editor = EditorGUIUtility.GetMainWindowPosition();
            var size = new Vector2(
                Mathf.Max(minimumSize.x, Mathf.Min(1000f, editor.width - 40f)),
                Mathf.Max(minimumSize.y, Mathf.Min(760f, editor.height - 80f)));
            window.position = new Rect(editor.center - size * 0.5f, size);
            return window;
        }

        /// <summary>Creates cached styles and window-owned textures in an active IMGUI context.</summary>
        public DocumentationEditorTheme()
        {
            Window = new GUIStyle { padding = new RectOffset(14, 14, 0, 10) };
            Title = Label(23, Text, true);
            Eyebrow = Label(10, Green, true);
            Body = Label(12, Text); Body.wordWrap = true;
            Small = Label(10, Muted); Small.wordWrap = true;
            Section = Label(14, Text, true); Section.wordWrap = true;
            Foldout = new GUIStyle(EditorStyles.foldout) { fontSize = 12, fontStyle = FontStyle.Bold, wordWrap = false, fixedHeight = 22 };
            for (int state = 0; state < 8; state++) State(Foldout, state).textColor = state % 4 == 1 || state % 4 == 3 ? Green : Text;
            Button = new GUIStyle(GUI.skin.button)
            {
                fontSize = 11, fontStyle = FontStyle.Bold, alignment = TextAnchor.MiddleCenter,
                border = new RectOffset(2, 2, 2, 2), padding = new RectOffset(8, 8, 4, 4),
                margin = new RectOffset(2, 2, 2, 2), wordWrap = false
            };
            SetState(Button.normal, Texture(Raised, Border), Text);
            SetState(Button.hover, Texture(new Color32(31, 58, 46, 255), Green), Green);
            SetState(Button.active, Texture(new Color32(48, 91, 64, 255), Green), Color.white);
            SetState(Button.focused, Texture(Raised, Green, 2), Green);
            SelectedButton = new GUIStyle(Button);
            SetState(SelectedButton.normal, Texture(new Color32(31, 65, 46, 255), Green), Green);
            SetState(SelectedButton.hover, Button.hover.background, Color.white);
            SetState(SelectedButton.active, Button.active.background, Color.white);
            SetState(SelectedButton.focused, Button.focused.background, Color.white);
            DangerButton = new GUIStyle(Button);
            SetState(DangerButton.normal, Texture(Raised, Error), Text);
            SetState(DangerButton.hover, Texture(Panel, Error), Error);
            SetState(DangerButton.focused, Texture(Raised, Error, 2), Error);
            SetState(DangerButton.active, Texture(Panel, Error, 2), Color.white);
            Log = Label(12, Text); Log.richText = true; Log.wordWrap = true;
            Log.padding = new RectOffset(14, 12, 10, 10);
            SetState(Log.hover, null, Color.white);
            SetState(Log.active, null, Color.white);
            Card = new GUIStyle { padding = new RectOffset(14, 14, 12, 12), margin = new RectOffset(0, 0, 0, 8) };
            Card.normal.background = Texture(Panel, Border);
            Card.border = new RectOffset(1, 1, 1, 1);
            Inspection = new GUIStyle(Body) { padding = new RectOffset(10, 10, 8, 8) };
            Inspection.normal.background = Texture(Background, Border);
            Inspection.border = new RectOffset(1, 1, 1, 1);
            _skin = UnityEngine.Object.Instantiate(GUI.skin);
            _skin.hideFlags = HideFlags.HideAndDontSave;
            _skin.button = Button; _skin.label = Body; _skin.box = Card;
            _readableStyles.AddRange(new[] { EditorStyles.label, EditorStyles.boldLabel, EditorStyles.miniLabel,
                EditorStyles.miniBoldLabel, EditorStyles.wordWrappedLabel, EditorStyles.wordWrappedMiniLabel,
                EditorStyles.foldout, EditorStyles.foldoutHeader, EditorStyles.toggle, EditorStyles.toggleGroup });
            IncludeButtonStyles(EditorStyles.miniButton, EditorStyles.miniButtonLeft, EditorStyles.miniButtonMid, EditorStyles.miniButtonRight);
            IncludePanelStyles(EditorStyles.helpBox);
#if ODIN_INSPECTOR
            IncludeLabelStyles(SirenixGUIStyles.Label, SirenixGUIStyles.BoldLabel, SirenixGUIStyles.BoxHeaderStyle, SirenixGUIStyles.Foldout);
            IncludeButtonStyles(SirenixGUIStyles.Button, SirenixGUIStyles.ButtonLeft, SirenixGUIStyles.ButtonMid, SirenixGUIStyles.ButtonRight);
            IncludePanelStyles(SirenixGUIStyles.BoxContainer);
#endif
        }

        /// <summary>Adds third-party label/foldout styles to this surface's temporary readability scope.</summary>
        /// <param name="styles">Label styles only; native input styles retain their matched host text/background.</param>
        public void IncludeLabelStyles(params GUIStyle[] styles)
        {
            if (_scopeDepth != 0) throw new InvalidOperationException("Register styles before entering the draw scope.");
            foreach (var style in styles) if (style != null && !_readableStyles.Contains(style)) _readableStyles.Add(style);
        }

        /// <summary>Includes cached button styles in the temporary scoped theme.</summary>
        /// <param name="styles">Third-party or Unity button styles used by this surface.</param>
        public void IncludeButtonStyles(params GUIStyle[] styles)
        {
            if (_scopeDepth != 0) throw new InvalidOperationException("Register styles before entering the draw scope.");
            foreach (var style in styles) if (style != null && !_buttonStyles.Contains(style)) _buttonStyles.Add(style);
        }

        /// <summary>Includes cached panel styles while preserving their layout and restoring their state.</summary>
        /// <param name="styles">Third-party or Unity panel styles used by this surface.</param>
        public void IncludePanelStyles(params GUIStyle[] styles)
        {
            if (_scopeDepth != 0) throw new InvalidOperationException("Register styles before entering the draw scope.");
            foreach (var style in styles) if (style != null && !_panelStyles.Contains(style)) _panelStyles.Add(style);
        }

        /// <summary>Temporarily themes default IMGUI buttons and labels; restores all shared styles on disposal.</summary>
        /// <returns>A scope to use around the owning window or inspector's draw call.</returns>
        public DrawScope Scope() => new DrawScope(this);

        /// <summary>Restores the previous GUI skin and label colours even if a drawer exits or throws.</summary>
        public readonly struct DrawScope : IDisposable
        {
            private readonly DocumentationEditorTheme _owner;
            internal DrawScope(DocumentationEditorTheme owner) { _owner = owner; owner.Enter(); }
            /// <summary>Restores the caller's IMGUI state at the outermost scope boundary.</summary>
            public void Dispose() => _owner?.Leave();
        }

        private void Enter()
        {
            if (_scopeDepth++ != 0) return;
            _previousSkin = GUI.skin; GUI.skin = _skin;
            int count = _readableStyles.Count * 8;
            if (_savedColors == null || _savedColors.Length != count) _savedColors = new Color[count];
            for (int i = 0; i < _readableStyles.Count; i++)
                for (int state = 0; state < 8; state++)
                {
                    var value = State(_readableStyles[i], state); _savedColors[i * 8 + state] = value.textColor;
                    value.textColor = state == 1 || state == 3 || state == 5 || state == 7 ? Green : Text;
                }
            int controls = _buttonStyles.Count + _panelStyles.Count;
            if (_savedBorders == null || _savedBorders.Length != controls)
            {
                _savedBorders = new RectOffset[controls]; _savedBackgrounds = new Texture2D[controls * 8]; _savedControlColors = new Color[controls * 8];
            }
            for (int i = 0; i < controls; i++)
            {
                bool button = i < _buttonStyles.Count;
                var style = button ? _buttonStyles[i] : _panelStyles[i - _buttonStyles.Count];
                // GUIStyle.border is a live native view, so save the values rather than that view.
                var border = style.border;
                if (_savedBorders[i] == null) _savedBorders[i] = new RectOffset();
                _savedBorders[i].left = border.left; _savedBorders[i].right = border.right;
                _savedBorders[i].top = border.top; _savedBorders[i].bottom = border.bottom;
                style.border = button ? Button.border : _thinBorder;
                for (int state = 0; state < 8; state++)
                {
                    var value = State(style, state);
                    _savedBackgrounds[i * 8 + state] = value.background; _savedControlColors[i * 8 + state] = value.textColor;
                    var source = State(button ? (state >= 4 ? SelectedButton : Button) : Card, state % 4);
                    value.background = source.background ?? Card.normal.background;
                    value.textColor = button ? source.textColor : Text;
                }
            }
        }

        private void Leave()
        {
            if (_scopeDepth == 0 || --_scopeDepth != 0) return;
            // Unwind in reverse order, including styles registered as both a label and control.
            for (int i = _savedBorders.Length - 1; i >= 0; i--)
            {
                var style = i < _buttonStyles.Count ? _buttonStyles[i] : _panelStyles[i - _buttonStyles.Count];
                style.border = _savedBorders[i];
                for (int state = 0; state < 8; state++)
                {
                    var value = State(style, state); value.background = _savedBackgrounds[i * 8 + state]; value.textColor = _savedControlColors[i * 8 + state];
                }
            }
            for (int i = _readableStyles.Count - 1; i >= 0; i--)
                for (int state = 0; state < 8; state++) State(_readableStyles[i], state).textColor = _savedColors[i * 8 + state];
            GUI.skin = _previousSkin;
        }

        private static GUIStyleState State(GUIStyle style, int state)
        {
            switch (state)
            {
                case 1: return style.hover; case 2: return style.active; case 3: return style.focused;
                case 4: return style.onNormal; case 5: return style.onHover; case 6: return style.onActive;
                case 7: return style.onFocused; default: return style.normal;
            }
        }

        /// <summary>Attaches the common USS theme without changing any other Unity or vendor surface.</summary>
        /// <param name="root">Owning window, modal, inspector, or package-extension subtree.</param>
        public static void ApplyToolkit(VisualElement root)
        {
            if (root == null) throw new ArgumentNullException(nameof(root));
            root.AddToClassList(RootClass);
            var sheet = AssetDatabase.LoadAssetAtPath<StyleSheet>(StyleSheetPath);
            if (sheet != null && !root.styleSheets.Contains(sheet)) root.styleSheets.Add(sheet);
        }

        /// <summary>Draws a numbered section heading with a concise wrapped description.</summary>
        /// <param name="index">Visible section identifier.</param>
        /// <param name="title">Readable task name.</param>
        /// <param name="description">Optional explanation.</param>
        public void Heading(string index, string title, string description)
        {
            GUILayout.Space(10);
            GUILayout.Label(index + "  /  " + title, Section);
            if (!string.IsNullOrEmpty(description)) GUILayout.Label(description, Small);
            GUILayout.Space(8);
        }

        /// <summary>Draws a semantic notice with both text and a colour indicator.</summary>
        /// <param name="title">Written state or required action.</param>
        /// <param name="message">Explanation and next step.</param>
        /// <param name="accent">Semantic colour, never the only state indication.</param>
        public void Notice(string title, string message, Color accent)
        {
            using (new EditorGUILayout.VerticalScope(Card))
            {
                var rect = GUILayoutUtility.GetRect(new GUIContent(title), Section);
                GUI.Label(rect, title, Section);
                EditorGUI.DrawRect(new Rect(rect.x - 13, rect.y - 11, 3, 20), accent);
                GUILayout.Space(4);
                GUILayout.Label(message, Body);
            }
        }

        private static GUIStyle Label(int size, Color color, bool bold = false)
        {
            var style = new GUIStyle(EditorStyles.label) { fontSize = size, fontStyle = bold ? FontStyle.Bold : FontStyle.Normal };
            for (int state = 0; state < 8; state++) State(style, state).textColor = color;
            return style;
        }

        private static void SetState(GUIStyleState state, Texture2D texture, Color color)
        {
            state.background = texture;
            state.textColor = color;
        }

        // Small nine-sliced textures avoid per-repaint allocations and do not ship bitmap assets.
        private Texture2D Texture(Color fill, Color edge, int thickness = 1)
        {
            var texture = new Texture2D(5, 5) { hideFlags = HideFlags.HideAndDontSave, filterMode = FilterMode.Point };
            var pixels = new Color[25];
            for (int y = 0; y < 5; y++)
                for (int x = 0; x < 5; x++)
                    pixels[y * 5 + x] = x < thickness || y < thickness || x >= 5 - thickness || y >= 5 - thickness ? edge : fill;
            texture.SetPixels(pixels); texture.Apply(); _textures.Add(texture);
            return texture;
        }

        /// <summary>Releases only this window's generated style textures on disable or script reload.</summary>
        public void Dispose()
        {
            while (_scopeDepth > 0) Leave();
            if (_skin != null) UnityEngine.Object.DestroyImmediate(_skin);
            _skin = null;
            foreach (var texture in _textures) UnityEngine.Object.DestroyImmediate(texture);
            _textures.Clear();
        }
    }
}
